apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
  labels:
    app: goserver
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - name: http
      port: 80
      targetPort: 8080
