apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-deploy
  labels:
    app: policy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy
  template:
    metadata:
      labels:
        app: policy
    spec:
      containers:
        - name: policy
          image: policy-service:local
          imagePullPolicy: IfNotPresent
          env:
            - name: CONSUL_HTTP_ADDR
              value: "http://consul:8500"
          ports:
            - containerPort: 8082
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-svc
  labels:
    app: policy
spec:
  type: ClusterIP
  selector:
    app: policy
  ports:
    - name: grpc
      port: 8082
      targetPort: 8082
